name: Bump version.txt
on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Bump version
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        last_tag=$(git tag | sort -V | tail -1)
        last_version=$(cat version.txt)
        if [ "$last_tag" = "$last_version" ]; then
          new_version=$(python .github/return_new_version.py $last_tag)
          echo $new_version > version.txt
          git commit --allow-empty -am "Version ${new_version}"
        fi
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.head_ref }}
